# Generated by Django 3.1.7 on 2024-08-01 12:43

from django.db import migrations, models

class Migration(migrations.Migration):

    dependencies = [
        ('backoffice', '0001_initial'),
    ]

    operations = [
        # Custom no-op migration operation
        migrations.RunPython(
            code=lambda apps, schema_editor: None,
            reverse_code=lambda apps, schema_editor: None
        ),
    ]
