# Generated by Django 3.2.24 on 2024-08-01 18:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backoffice', '0002_auto_20240801_1443'),
        ('backoffice', '0002_no_op_migration'),
    ]

    operations = [
    ]
